package com.jdndeveloper.lifereminders.storage;

/**
 * Created by Jayden Navarro on 3/10/2015.
 */
public class Presets {
    public final static String Preset_Lifestyle_01 = "{\"lifestyleReminders\":[\"Preset_Reminder_01\",\"Preset_Reminder_02\",\"Preset_Reminder_03\"],\"key\":\"Preset_Lifestyle_01\",\"name\":\"Chores\",\"enabled\":false}";
    public final static String Preset_Lifestyle_02 = "{\"lifestyleReminders\":[\"Preset_Reminder_04\",\"Preset_Reminder_05\"],\"key\":\"Preset_Lifestyle_02\",\"name\":\"Fitness\",\"enabled\":false}";
    public final static String Preset_Lifestyle_03 = "{\"lifestyleReminders\":[\"Preset_Reminder_06\",\"Preset_Reminder_07\"],\"key\":\"Preset_Lifestyle_03\",\"name\":\"Daily Routine\",\"enabled\":false}";

    public final static String Preset_Reminder_01 = "{\"lifestyleContainerKey\":\"Preset_Lifestyle_01\",\"notificationKeys\":[\"Preset_Notification_01\"],\"key\":\"Preset_Reminder_01\",\"name\":\"Take out the trash\",\"enabled\":false}";
    public final static String Preset_Reminder_02 = "{\"lifestyleContainerKey\":\"Preset_Lifestyle_01\",\"notificationKeys\":[\"Preset_Notification_02\"],\"key\":\"Preset_Reminder_02\",\"name\":\"Wash the dishes\",\"enabled\":false}";
    public final static String Preset_Reminder_03 = "{\"lifestyleContainerKey\":\"Preset_Lifestyle_01\",\"notificationKeys\":[\"Preset_Notification_03\",\"Preset_Notification_04\"],\"key\":\"Preset_Reminder_03\",\"name\":\"Walk the dog\",\"enabled\":false}";
    public final static String Preset_Reminder_04 = "{\"lifestyleContainerKey\":\"Preset_Lifestyle_02\",\"notificationKeys\":[\"Preset_Notification_05\"],\"key\":\"Preset_Reminder_04\",\"name\":\"Take supplements\",\"enabled\":false}";
    public final static String Preset_Reminder_05 = "{\"lifestyleContainerKey\":\"Preset_Lifestyle_02\",\"notificationKeys\":[\"Preset_Notification_06\"],\"key\":\"Preset_Reminder_05\",\"name\":\"Go to the gym\",\"enabled\":false}";
    public final static String Preset_Reminder_06 = "{\"lifestyleContainerKey\":\"Preset_Lifestyle_03\",\"notificationKeys\":[\"Preset_Notification_07\",\"Preset_Notification_08\"],\"key\":\"Preset_Reminder_06\",\"name\":\"Brush Teeth\",\"enabled\":false}";
    public final static String Preset_Reminder_07 = "{\"lifestyleContainerKey\":\"Preset_Lifestyle_03\",\"notificationKeys\":[\"Preset_Notification_09\"],\"key\":\"Preset_Reminder_07\",\"name\":\"Shower\",\"enabled\":false}";

    public final static String Preset_Notification_01 = "{\"actionKey\":\"Preset_Action_01\",\"calendar\":{\"year\":2015,\"month\":2,\"dayOfMonth\":9,\"hourOfDay\":19,\"minute\":0,\"second\":0},\"lifestyleContainerKey\":\"Preset_Lifestyle_01\",\"reminderContainerKey\":\"Preset_Reminder_01\",\"repeatDays\":[3],\"repeatDaysEnabled\":true,\"repeatEveryBlankDays\":0,\"repeatEveryBlankDaysEnabled\":false,\"key\":\"Preset_Notification_01\",\"name\":\"New Preset_Notification_01\",\"enabled\":false}";
    public final static String Preset_Notification_02 = "{\"actionKey\":\"Preset_Action_02\",\"calendar\":{\"year\":2015,\"month\":2,\"dayOfMonth\":10,\"hourOfDay\":18,\"minute\":0,\"second\":0},\"lifestyleContainerKey\":\"Preset_Lifestyle_01\",\"reminderContainerKey\":\"Preset_Reminder_02\",\"repeatDays\":[],\"repeatDaysEnabled\":false,\"repeatEveryBlankDays\":1,\"repeatEveryBlankDaysEnabled\":true,\"key\":\"Preset_Notification_02\",\"name\":\"\",\"enabled\":false}";
    public final static String Preset_Notification_03 = "{\"actionKey\":\"Preset_Action_03\",\"calendar\":{\"year\":2015,\"month\":2,\"dayOfMonth\":10,\"hourOfDay\":10,\"minute\":0,\"second\":0},\"lifestyleContainerKey\":\"Preset_Lifestyle_01\",\"reminderContainerKey\":\"Preset_Reminder_03\",\"repeatDays\":[],\"repeatDaysEnabled\":false,\"repeatEveryBlankDays\":1,\"repeatEveryBlankDaysEnabled\":true,\"key\":\"Preset_Notification_03\",\"name\":\"\",\"enabled\":false}";
    public final static String Preset_Notification_04 = "{\"actionKey\":\"Preset_Action_04\",\"calendar\":{\"year\":2015,\"month\":2,\"dayOfMonth\":10,\"hourOfDay\":16,\"minute\":30,\"second\":0},\"lifestyleContainerKey\":\"Preset_Lifestyle_01\",\"reminderContainerKey\":\"Preset_Reminder_03\",\"repeatDays\":[],\"repeatDaysEnabled\":false,\"repeatEveryBlankDays\":1,\"repeatEveryBlankDaysEnabled\":true,\"key\":\"Preset_Notification_04\",\"name\":\"\",\"enabled\":false}";
    public final static String Preset_Notification_05 = "{\"actionKey\":\"Preset_Action_05\",\"calendar\":{\"year\":2015,\"month\":2,\"dayOfMonth\":10,\"hourOfDay\":14,\"minute\":0,\"second\":0},\"lifestyleContainerKey\":\"Preset_Lifestyle_02\",\"reminderContainerKey\":\"Preset_Reminder_04\",\"repeatDays\":[],\"repeatDaysEnabled\":false,\"repeatEveryBlankDays\":1,\"repeatEveryBlankDaysEnabled\":true,\"key\":\"Preset_Notification_05\",\"name\":\"\",\"enabled\":false}";
    public final static String Preset_Notification_06 = "{\"actionKey\":\"Preset_Action_06\",\"calendar\":{\"year\":2015,\"month\":2,\"dayOfMonth\":9,\"hourOfDay\":9,\"minute\":0,\"second\":0},\"lifestyleContainerKey\":\"Preset_Lifestyle_02\",\"reminderContainerKey\":\"Preset_Reminder_05\",\"repeatDays\":[2,4,6],\"repeatDaysEnabled\":true,\"repeatEveryBlankDays\":0,\"repeatEveryBlankDaysEnabled\":false,\"key\":\"Preset_Notification_06\",\"name\":\"New Preset_Notification_06\",\"enabled\":false}";
    public final static String Preset_Notification_07 = "{\"actionKey\":\"Preset_Action_07\",\"calendar\":{\"year\":2015,\"month\":2,\"dayOfMonth\":10,\"hourOfDay\":8,\"minute\":0,\"second\":0},\"lifestyleContainerKey\":\"Preset_Lifestyle_03\",\"reminderContainerKey\":\"Preset_Reminder_06\",\"repeatDays\":[],\"repeatDaysEnabled\":false,\"repeatEveryBlankDays\":1,\"repeatEveryBlankDaysEnabled\":true,\"key\":\"Preset_Notification_07\",\"name\":\"\",\"enabled\":false}";
    public final static String Preset_Notification_08 = "{\"actionKey\":\"Preset_Action_08\",\"calendar\":{\"year\":2015,\"month\":2,\"dayOfMonth\":10,\"hourOfDay\":21,\"minute\":0,\"second\":0},\"lifestyleContainerKey\":\"Preset_Lifestyle_03\",\"reminderContainerKey\":\"Preset_Reminder_06\",\"repeatDays\":[],\"repeatDaysEnabled\":false,\"repeatEveryBlankDays\":1,\"repeatEveryBlankDaysEnabled\":true,\"key\":\"Preset_Notification_08\",\"name\":\"\",\"enabled\":false}";
    public final static String Preset_Notification_09 = "{\"actionKey\":\"Preset_Action_09\",\"calendar\":{\"year\":2015,\"month\":2,\"dayOfMonth\":10,\"hourOfDay\":22,\"minute\":0,\"second\":0},\"lifestyleContainerKey\":\"Preset_Lifestyle_03\",\"reminderContainerKey\":\"Preset_Reminder_07\",\"repeatDays\":[],\"repeatDaysEnabled\":false,\"repeatEveryBlankDays\":1,\"repeatEveryBlankDaysEnabled\":true,\"key\":\"Preset_Notification_09\",\"name\":\"\",\"enabled\":false}";

    public final static String Preset_Action_01 = "{\"cameraLight\":false,\"ringtoneDuration\":5000,\"vibrateDuration\":500,\"notificationBar\":true,\"notificationSound\":true,\"ringtoneSound\":false,\"vibrate\":false,\"key\":\"Preset_Action_01\",\"name\":\"New Preset_Action_01\",\"enabled\":true}";
    public final static String Preset_Action_02 = "{\"cameraLight\":false,\"ringtoneDuration\":5000,\"vibrateDuration\":500,\"notificationBar\":true,\"notificationSound\":true,\"ringtoneSound\":false,\"vibrate\":false,\"key\":\"Preset_Action_02\",\"name\":\"New Preset_Action_02\",\"enabled\":true}";
    public final static String Preset_Action_03 = "{\"cameraLight\":false,\"ringtoneDuration\":5000,\"vibrateDuration\":500,\"notificationBar\":true,\"notificationSound\":true,\"ringtoneSound\":false,\"vibrate\":false,\"key\":\"Preset_Action_03\",\"name\":\"New Preset_Action_03\",\"enabled\":true}";
    public final static String Preset_Action_04 = "{\"cameraLight\":false,\"ringtoneDuration\":5000,\"vibrateDuration\":500,\"notificationBar\":true,\"notificationSound\":true,\"ringtoneSound\":false,\"vibrate\":false,\"key\":\"Preset_Action_04\",\"name\":\"New Preset_Action_04\",\"enabled\":true}";
    public final static String Preset_Action_05 = "{\"cameraLight\":false,\"ringtoneDuration\":5000,\"vibrateDuration\":500,\"notificationBar\":true,\"notificationSound\":true,\"ringtoneSound\":false,\"vibrate\":true,\"key\":\"Preset_Action_05\",\"name\":\"New Preset_Action_05\",\"enabled\":true}";
    public final static String Preset_Action_06 = "{\"cameraLight\":false,\"ringtoneDuration\":5000,\"vibrateDuration\":500,\"notificationBar\":true,\"notificationSound\":true,\"ringtoneSound\":false,\"vibrate\":false,\"key\":\"Preset_Action_06\",\"name\":\"New Preset_Action_06\",\"enabled\":true}";
    public final static String Preset_Action_07 = "{\"cameraLight\":false,\"ringtoneDuration\":5000,\"vibrateDuration\":500,\"notificationBar\":true,\"notificationSound\":false,\"ringtoneSound\":false,\"vibrate\":true,\"key\":\"Preset_Action_07\",\"name\":\"New Preset_Action_07\",\"enabled\":true}";
    public final static String Preset_Action_08 = "{\"cameraLight\":false,\"ringtoneDuration\":5000,\"vibrateDuration\":500,\"notificationBar\":true,\"notificationSound\":false,\"ringtoneSound\":false,\"vibrate\":true,\"key\":\"Preset_Action_08\",\"name\":\"New Preset_Action_08\",\"enabled\":true}";
    public final static String Preset_Action_09 = "{\"cameraLight\":false,\"ringtoneDuration\":5000,\"vibrateDuration\":500,\"notificationBar\":true,\"notificationSound\":true,\"ringtoneSound\":false,\"vibrate\":false,\"key\":\"Preset_Action_09\",\"name\":\"New Preset_Action_09\",\"enabled\":true}";
}
